# FILE: docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: trishop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - trishop_network
    depends_on:
      - db
      - redis
      - elasticsearch

  web:
    image: nginx:alpine
    container_name: trishop_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - trishop_network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: trishop_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - trishop_network

  redis:
    image: redis:7-alpine
    container_name: trishop_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    networks:
      - trishop_network

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: trishop_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - trishop_network

networks:
  trishop_network:
    driver: bridge

volumes:
  dbdata:
  redisdata:
  esdata: